# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  levels: one
  folders:

  - title: Managed Application Delivery Services
    output: web
    folderitems:
    - title: Managed Application Delivery Services
      url: /mad_managed_application_delivery_services.html
      output: web
    - title: What is Managed Application Delivery Service?
      url: /mad_what_is_managed_application_delivery_service.html
      output: web
    - title: About Liquit Workspace?
      url: /mad_about_liquit_workspace.html
      output: web


  - title: Liquit as a Service Infrastructure
    output: web
    folderitems:
    - title: Liquit As A Service Infrastructure
      url: /mad_liquitasaservice_main.html
      output: web
    - title: Liquit Workspace Server
      url: /mad_liquitasaservice_liquitserver.html
      output: web
    - title: Liquit Workspace Satelite Server
      url: /mad_liquitasaservice_liquitsateliteserver.html
      output: web
    - title: Content Store - Azure Blob
      url: /mad_liquitasaservice_azureblob.html
      output: web
    - title: Microsoft Azure SQL Database
      url: /mad_liquitasaservice_azure_sql_database.html
      output: web
    - title: Microsoft Azure Loadbalancer
      url: /mad_liquitasaservice_azure_loadbalancer.html
      output: web




  - title: Liquit Workspace - Cookbook
    output: web
    folderitems:
    - title: Liquit Workspace - Cookbook
      url: /mad_liquit_workspace_cookbook.html
      output: web
    - title: Liquit Workspace - Identities
      url: /mad_liquit_workspace_identities.html
      output: web
    - title: Liquit Workspace - Workpace
      url: /mad_liquit_workspace_workspace.html
      output: web
    - title: Liquit Workspace - Automation
      url: /mad_liquit_workspace_automation.html
      output: web
    - title: Liquit Workspace - Portal
      url: /mad_liquit_workspace_portal.html
      output: web
    - title: Liquit Workspace - Authentication
      url: /mad_liquit_workspace_authentication.html
      output: web
    - title: Liquit Workspace - System
      url: /mad_liquit_workspace_system.html
      output: web
    - title: Liquit Workspace - Agent
      url: /mad_liquit_workspace_agent.html
      output: web
    - title: Liquit Workspace - Design Decisions
      url: /mad_liquit_workspace_designdecisions.html
      output: web



  - title: Liquit Workspace - Runbook
    output: web
    folderitems:
    - title: Liquit Workspace - Runbook
      url: /mad_liquit_workspace_runbook.html
      output: web
    - title: Liquit Workspace - Onboarding
      url: /mad_liquit_workspace_onboarding.html
      output: web
    - title: Liquit Workspace - Standard Changes
      url: /mad_liquit_workspace_standardchanges.html
      output: web
    - title: Liquit Workspace - Maintenance
      url: /mad_liquit_workspace_maintenance.html
      output: web






# Copyright 2021 Google LLC
