# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  levels: one
  folders:

  - title: Managed Application Delivery Services
    output: web
    folderitems:
    - title: Managed Application Delivery Services
      url: /mad_managed_application_delivery_services.html
      output: web
    - title: What is Managed Application Delivery Service?
      url: /mad_what_is_managed_application_delivery_service.html
      output: web
      - title: About Liquit Workspace?
        url: /mad_about_liquit_workspace.html
        output: web


  - title: Liquit as a Service Infrastructure
    output: web
    folderitems:
    - title: Liquit Workspace Cloud Infrastructure
      url: /mad_liquit_workspace_cloud_infrastructure.html
      output: web
    - title: Liquit Workspace - Cookbook
      url: /mad_liquit_workspace_cookbook.html
      output: web
    - title: Liquit Workspace - Runbook
      url: /mad_liquit_workspace_runbook.html
      output: web



  - title: Liquit Workspace - Cookbook
    output: web
    folderitems:
    - title: Liquit Release & Patch Management
      url: /mad_liquit_release_and_patchmanagement.html
      output: web
    - title: Liquit Workspace Cloud Infrastructure
      url: /mad_liquit_workspace_cloud_infrastructure.html
      output: web
    - title: Liquit Workspace - Cookbook
      url: /mad_liquit_workspace_cookbook.html
      output: web
    - title: Liquit Workspace - Runbook
      url: /mad_liquit_workspace_runbook.html
      output: web


  - title: Liquit Workspace - Runbook
    output: web
    folderitems:
    - title: About Liquit Workspace?
      url: /mad_about_liquit_workspace.html
      output: web
    - title: Liquit Release & Patch Management
      url: /mad_liquit_release_and_patchmanagement.html
      output: web
    - title: Liquit Workspace Cloud Infrastructure
      url: /mad_liquit_workspace_cloud_infrastructure.html
      output: web
    - title: Liquit Workspace - Cookbook
      url: /mad_liquit_workspace_cookbook.html
      output: web
    - title: Liquit Workspace - Runbook
      url: /mad_liquit_workspace_runbook.html
      output: web
# Copyright 2021 Google LLC
